//! An end-to-end example of using the SP1 SDK to generate a proof of a program that can be executed
//! or have a core proof generated.
//!
//! You can run this script using the following command:
//! ```shell
//! RUST_LOG=info cargo run --release -- --execute
//! ```
//! or
//! ```shell
//! RUST_LOG=info cargo run --release -- --prove
//! ```

// use env_logger;
// use log::{error, info, warn};
use serde::{Deserialize, Serialize};
use sp1_sdk::{include_elf, utils, ProverClient, SP1ProofWithPublicValues, SP1Stdin};
use alloy_sol_types::SolType;
use lib::{fibonacci, ImageDetailData};


/// The ELF we want to execute inside the zkVM.
const ELF: &[u8] = include_elf!("zk-attestation-for-ai-generated-contents-program");
//const ELF: &[u8] = include_elf!("chess-program"); /// @dev - "chess-program" is referenced from the program/Cargo.toml

#[derive(Serialize, Deserialize)]
struct ImageData {
    id: u32,
    height: u32,
    width: u32,
    image_name: String,
    image_extension: String,
}

/**
 * @notice - The test of the main() in the main.rs of the /program.
 */
fn main() {
    // Setup logging.
    utils::setup_logger();
    dotenv::dotenv().ok();

    // Create an input stream (image data, which is generated by AI)
    let _id: u32 = 1;
    let _height: u32 = 200;
    let _width: u32 = 150;
    let _image_name: String = "test-image".to_string();
    let _image_extension: String = "jpg".to_string();

    let test: u32 = 11;

    let image_data: ImageData = ImageData {
        id: _id,
        height: _height,
        width: _width,
        image_name: _image_name,
        image_extension: _image_extension,
    };

    // The input stream that the program will read from using `sp1_zkvm::io::read`.
    let mut stdin = SP1Stdin::new();
    //stdin.write(&image_data);
    stdin.write(&test); // For test

    println!("Image ID: {}", image_data.id);
    println!("Image Height: {}", image_data.height);
    println!("Image Width: {}", image_data.width);
    println!("Image Name: {}", image_data.image_name);
    println!("Image Extension: {}", image_data.image_extension);

    // Create a `ProverClient` method.
    let client = ProverClient::from_env();

    // Execute the program using the `ProverClient.execute` method, without generating a proof.
    let (_, report) = client.execute(ELF, &stdin).run().unwrap(); // [Error]: thread 'main' panicked
    println!(
        "executed program with {} cycles",
        report.total_instruction_count()
    );

    // Generate the proof for the given program and input.
    let (pk, vk) = client.setup(ELF);
    let mut proof = client.prove(&pk, &stdin).run().unwrap();
    println!("Successfully generated proof!");

    // Verify the proof.
    client.verify(&proof, &vk).expect("failed to verify proof");
    println!("Successfully verified proof!");
}
