[package]
name = "zk-attestation-for-ai-generated-contents-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
